import { useEffect, useState } from 'react';

export default function ProductPurchasePanel({ slug }: { slug: string }) {
  const [item, setItem] = useState<any>(null); const [services, setServices] = useState<any[]>([]); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch('/api/store/catalog').then((response) => response.json()).then((data) => { const all = data.items || []; setItem(all.find((entry: any) => entry.slug === slug)); setServices(all.filter((entry: any) => entry.productType === 'setup_service' && entry.includedProductSlugs?.includes(slug))); }); }, [slug]);
  const checkout = async (acknowledgeOwned = false) => { setBusy(true); const auth = await fetch('/api/auth/session').then((response) => response.json()); if (!auth.authenticated) { location.href = `/api/auth/discord?action=login&returnTo=${encodeURIComponent(location.pathname)}`; return; } const response = await fetch('/api/store/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': auth.csrfToken }, body: JSON.stringify({ productSlugs: [slug], setupServiceSlugs: selected, acknowledgeOwned }) }); const data = await response.json(); if (response.ok) { location.href = data.checkoutUrl; return; } if (data.code === 'existing_entitlement' && confirm('You already own this product. Continue and purchase it again?')) return checkout(true); setMessage(data.error || 'Unable to start checkout'); setBusy(false); };
  if (!item) return <div className="purchase-panel loading">Loading live price and availability…</div>;
  const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
  return <aside className="purchase-panel"><div><span>One-time purchase</span><strong>{item.price?.isStartingAt ? 'Starting at ' : ''}{money(item.sale?.amountCents ?? item.price?.amountCents ?? 0)}</strong>{item.sale && <small>Normally {money(item.price.amountCents)} · Save {money(item.sale.savingsCents)}</small>}</div>{services.length > 0 && <fieldset><legend>Optional setup</legend>{services.map((service) => <label><input type="checkbox" checked={selected.includes(service.slug)} onChange={() => setSelected((current) => current.includes(service.slug) ? current.filter((value) => value !== service.slug) : [...current, service.slug])} /><span>{service.name}<small>{service.price?.isStartingAt ? 'Starting at ' : ''}{money(service.price?.amountCents || 0)}</small></span></label>)}</fieldset>}<button disabled={!item.purchasable || busy} onClick={() => checkout()}>{busy ? 'Preparing secure checkout…' : item.purchasable ? 'Buy Now With Stripe' : 'Currently Unavailable'}</button><p>Stripe handles payment details. Access is fulfilled after the verified Stripe webhook completes.</p>{message && <div className="purchase-error">{message}</div>}<style>{`.purchase-panel{display:grid;gap:16px;padding:22px;border:1px solid rgba(168,85,247,.32);border-radius:16px;background:rgba(18,18,25,.8)}.purchase-panel>div span{display:block;color:#aaa;font-size:.75rem;text-transform:uppercase;letter-spacing:.1em}.purchase-panel>div strong{display:block;font-size:2rem}.purchase-panel>div small{color:#6ee7b7}.purchase-panel fieldset{display:grid;gap:8px;border:0;padding:0}.purchase-panel legend{margin-bottom:8px;font-weight:800}.purchase-panel label{display:flex;gap:10px;padding:10px;border:1px solid rgba(168,85,247,.14);border-radius:8px}.purchase-panel label span{display:flex;justify-content:space-between;width:100%;gap:10px}.purchase-panel label small{color:#aaa}.purchase-panel button{padding:13px;border:0;border-radius:9px;background:linear-gradient(135deg,#a855f7,#6d28d9);color:#fff;font-weight:800;cursor:pointer}.purchase-panel button:disabled{opacity:.5}.purchase-panel p{margin:0;color:#888;font-size:.78rem}.purchase-error{padding:10px;border:1px solid #ff7086;border-radius:8px;color:#ff9aac}`}</style></aside>;
}

